// 常用出生地点（经度 + 时区中央经线）。
//   lon: °E 为正、°W 为负
//   tzMeridian: 该地常用 UTC 偏移 × 15（按标准时算，与是否实行夏令时无关）
//   注意：中国全境一律 UTC+8 → tzMeridian = 120

export const BIRTH_PLACES = [
  { id: "beijing",      group: "中国大陆", name: "北京",     lon: 116.41, tzMeridian: 120 },
  { id: "shanghai",     group: "中国大陆", name: "上海",     lon: 121.47, tzMeridian: 120 },
  { id: "guangzhou",    group: "中国大陆", name: "广州",     lon: 113.26, tzMeridian: 120 },
  { id: "shenzhen",     group: "中国大陆", name: "深圳",     lon: 114.06, tzMeridian: 120 },
  { id: "chengdu",      group: "中国大陆", name: "成都",     lon: 104.07, tzMeridian: 120 },
  { id: "chongqing",    group: "中国大陆", name: "重庆",     lon: 106.55, tzMeridian: 120 },
  { id: "wuhan",        group: "中国大陆", name: "武汉",     lon: 114.30, tzMeridian: 120 },
  { id: "nanjing",      group: "中国大陆", name: "南京",     lon: 118.78, tzMeridian: 120 },
  { id: "hangzhou",     group: "中国大陆", name: "杭州",     lon: 120.16, tzMeridian: 120 },
  { id: "xian",         group: "中国大陆", name: "西安",     lon: 108.95, tzMeridian: 120 },
  { id: "harbin",       group: "中国大陆", name: "哈尔滨",   lon: 126.53, tzMeridian: 120 },
  { id: "shenyang",     group: "中国大陆", name: "沈阳",     lon: 123.43, tzMeridian: 120 },
  { id: "tianjin",      group: "中国大陆", name: "天津",     lon: 117.20, tzMeridian: 120 },
  { id: "qingdao",      group: "中国大陆", name: "青岛",     lon: 120.38, tzMeridian: 120 },
  { id: "xiamen",       group: "中国大陆", name: "厦门",     lon: 118.09, tzMeridian: 120 },
  { id: "changsha",     group: "中国大陆", name: "长沙",     lon: 112.94, tzMeridian: 120 },
  { id: "zhengzhou",    group: "中国大陆", name: "郑州",     lon: 113.62, tzMeridian: 120 },
  { id: "kunming",      group: "中国大陆", name: "昆明",     lon: 102.83, tzMeridian: 120 },
  { id: "urumqi",       group: "中国大陆", name: "乌鲁木齐", lon:  87.62, tzMeridian: 120 },
  { id: "lhasa",        group: "中国大陆", name: "拉萨",     lon:  91.13, tzMeridian: 120 },
  { id: "hongkong",     group: "港澳台",   name: "香港",     lon: 114.16, tzMeridian: 120 },
  { id: "macao",        group: "港澳台",   name: "澳门",     lon: 113.55, tzMeridian: 120 },
  { id: "taipei",       group: "港澳台",   name: "台北",     lon: 121.56, tzMeridian: 120 },
  { id: "tokyo",        group: "亚洲",     name: "东京",     lon: 139.69, tzMeridian: 135 },
  { id: "osaka",        group: "亚洲",     name: "大阪",     lon: 135.50, tzMeridian: 135 },
  { id: "seoul",        group: "亚洲",     name: "首尔",     lon: 126.98, tzMeridian: 135 },
  { id: "singapore",    group: "亚洲",     name: "新加坡",   lon: 103.82, tzMeridian: 120 },
  { id: "bangkok",      group: "亚洲",     name: "曼谷",     lon: 100.50, tzMeridian: 105 },
  { id: "kualalumpur",  group: "亚洲",     name: "吉隆坡",   lon: 101.69, tzMeridian: 120 },
  { id: "jakarta",      group: "亚洲",     name: "雅加达",   lon: 106.85, tzMeridian: 105 },
  { id: "delhi",        group: "亚洲",     name: "新德里",   lon:  77.21, tzMeridian:  82.5 },
  { id: "newyork",      group: "北美",     name: "纽约",     lon: -74.01, tzMeridian: -75 },
  { id: "boston",       group: "北美",     name: "波士顿",   lon: -71.06, tzMeridian: -75 },
  { id: "washington",   group: "北美",     name: "华盛顿",   lon: -77.04, tzMeridian: -75 },
  { id: "toronto",      group: "北美",     name: "多伦多",   lon: -79.38, tzMeridian: -75 },
  { id: "montreal",     group: "北美",     name: "蒙特利尔", lon: -73.57, tzMeridian: -75 },
  { id: "chicago",      group: "北美",     name: "芝加哥",   lon: -87.65, tzMeridian: -90 },
  { id: "houston",      group: "北美",     name: "休斯顿",   lon: -95.37, tzMeridian: -90 },
  { id: "denver",       group: "北美",     name: "丹佛",     lon: -104.99, tzMeridian: -105 },
  { id: "sanfrancisco", group: "北美",     name: "旧金山",   lon: -122.42, tzMeridian: -120 },
  { id: "sanjose",      group: "北美",     name: "圣何塞",   lon: -121.89, tzMeridian: -120 },
  { id: "losangeles",   group: "北美",     name: "洛杉矶",   lon: -118.24, tzMeridian: -120 },
  { id: "seattle",      group: "北美",     name: "西雅图",   lon: -122.33, tzMeridian: -120 },
  { id: "vancouver",    group: "北美",     name: "温哥华",   lon: -123.12, tzMeridian: -120 },
  { id: "london",       group: "欧洲",     name: "伦敦",     lon:  -0.13, tzMeridian:   0 },
  { id: "paris",        group: "欧洲",     name: "巴黎",     lon:   2.35, tzMeridian:  15 },
  { id: "berlin",       group: "欧洲",     name: "柏林",     lon:  13.40, tzMeridian:  15 },
  { id: "rome",         group: "欧洲",     name: "罗马",     lon:  12.50, tzMeridian:  15 },
  { id: "madrid",       group: "欧洲",     name: "马德里",   lon:  -3.70, tzMeridian:  15 },
  { id: "moscow",       group: "欧洲",     name: "莫斯科",   lon:  37.62, tzMeridian:  45 },
  { id: "sydney",       group: "大洋洲",   name: "悉尼",     lon: 151.21, tzMeridian: 150 },
  { id: "melbourne",    group: "大洋洲",   name: "墨尔本",   lon: 144.96, tzMeridian: 150 },
  { id: "auckland",     group: "大洋洲",   name: "奥克兰",   lon: 174.76, tzMeridian: 180 },
];
